version: '3.8'

services:
  workspace_service:
    build:
      context: .
      dockerfile: Dockerfile
    command: [ 'sleep', 'infinity' ]
    user: dev
    depends_on:
      - postgis_service
    volumes:
      - ..:/workspace:cached
    ports:
      - 3000:3000
    networks:
      caleghub_network:

  postgis_service:
    image: postgis/postgis:15-3.4-alpine
    environment:
      POSTGRES_DB: caleghub
      POSTGRES_USER: caleghub
      POSTGRES_PASSWORD: caleghub
    volumes:
      - postgis_volume:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      caleghub_network:

volumes:
  postgis_volume:

networks:
  caleghub_network:
